Link to log files: https://drive.google.com/open?id=13ubKUJmAWPXQu1R_GCxB8W-L6dqEnyoG

To execute this project:

 - You need to have a directory called _logs. You'll find one with this download, if not, run `mkdir _logs`
 - You need to have *CMake* (cmake.org) minimum version 2.8 installed
 - You need to have *make* installed

To compile the project the following commands:
cmake .
make 
./meta

Nevertheless, you can find a Makefile already pre-generated by me from the CMakeFile in case you don't want to install CMake. make
should be available in all UNIX distributions. 

You can run the pre-compiled program by executing the command 
./meta